### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by jieWANGforwork** [wzsong17/COCO-SBRS#1]
Hi, where is the dataset, data preprocessing code, testing data, and the evaluation code? Can you provide for reproduce?

**Comment by epiphany8** [comment]
May I ask what the complete project catalog looks like? Because I ran the code and received the prompt 'FileNotFoundError: [Errno 2] No such file or directory:' D: PyCharmProjects COCO SBRS data fm_delicious_0. pkl '?'

**Comment by wzsong17** [comment]
Hi all, I have uploaded the missing files.
